SALCHICHA POLLO Y PAVO TOVAR ASADA
SALCHICHA WINNER TOVAR ASADA
SALCHICHA POLACA TOVAR ASADA
SALCHICHA WINNER HERMO LARGA ASADA
PAN PERROCALIENTE PEQ AL VAPOR
PORCION DE PAPITAS FRITAS PARA PERROCALIENTE
TETERO 700ML DE MAYONESA PREPARADA
TETERO 700ML DE KETCHUP (SALSA DE TOMATE)
TETERO 700ML SALSA TARTARA
REFRESCO 400ML
NESTEA 400ML
